version: '3'
services:
  tinyproxy:
    image: dannydirect/tinyproxy
    container_name: tinyproxy
    ports:
      - "8888:8888"
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
